version: '3'
services:
  key-manager-grpc:
    build:
      context: .
    image: rochards/key-manager-grpc
    container_name: key-manager-grpc
    ports:
    - 50051:50051
    depends_on:
      - key-manager-grpc-db
      - bcb
      - erp-itau
    environment:
      DB_URL: jdbc:mysql://key-manager-grpc-db:3306/pix_db?serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: root
      BCB_URL: http://bcb:8082
      ERP_ITAU_URL: http://erp-itau:9091

  key-manager-grpc-db:
    build:
      context: database
    image: rochards/key-manager-grpc-db
    container_name: key-manager-grpc-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pix_db
    volumes:
    - mysql-volume:/var/lib/mysql

  bcb:
    image: public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix
    container_name: bcb

  erp-itau:
    image: public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp
    container_name: erp-itau

volumes:
  mysql-volume:
