micronaut:
  application:
    name: keyManagerGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DB_URL:`jdbc:mysql://localhost:3306/pix_db?serverTimezone=UTC`}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:123456}
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update

erp-itau.url: ${ERP_ITAU_URL:`http://localhost:9091`}
bcb.url: ${BCB_URL:`http://localhost:8082`}
